FROM node:20

WORKDIR /app

# Copy only package.json + lock first
COPY frontend/package*.json ./

# Clean install without optional deps issues
RUN npm install --legacy-peer-deps

# Copy source code
COPY frontend/ .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
