version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: memory_gpt_postgres
    environment:
      POSTGRES_DB: memory_gpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - memorygpt_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: memory_gpt_backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - memorygpt_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: memory_gpt_frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - memorygpt_net

volumes:
  pgdata:

networks:
  memorygpt_net: