version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: memory_gpt_postgres
    environment:
      POSTGRES_DB: memory_gpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  pgdata:
